version: "3.8"
services:
  app:
    container_name: crypto-service-app
    build: "."
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - "postgres_db"
  postgres_db:
    image: "postgres"
    container_name: "crypto-service-postgres"
    restart: "unless-stopped"
    env_file:
      - ".env"
    ports:
      - "5445:5432"