postgres:
  host: "localhost"
  port: "5432"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 300
logger:
  # -1 - trace level
  # 0 - debug level
  # 1 - info level
  # 2 - warn level
  # 3 - error level
  # 4 - fatal level
  # 5 - panic level
  # 6 - no level
  # 7 - disabled
  log_level: 0